name: MXD-env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - about-time=4.2.1=pyhd8ed1ab_1
  - alive-progress=3.0.1=pyhd8ed1ab_0
  - anaconda-anon-usage=0.7.0=py313hfc0e8ea_101
  - annotated-types=0.6.0=py313h06a4308_0
  - aragorn=1.2.41=h7b50bb2_5
  - archspec=0.2.3=pyhd3eb1b0_0
  - bakta=1.8.1=pyhdfd78af_0
  - biopython=1.86=py313h07c4f96_0
  - blas=1.0=mkl
  - blast=2.16.0=hc155240_3
  - boltons=24.1.0=py313h06a4308_0
  - bottleneck=1.4.2=py313haa0f9ac_1
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - circos=0.69.9=hdfd78af_0
  - conda=25.11.1=py313h78bf25f_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.1.3=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=44.0.1=py313h7825ff9_0
  - curl=8.12.1=h251f7ec_0
  - diamond=2.1.10=h43eeafb_2
  - distro=1.9.0=py313h06a4308_0
  - entrez-direct=22.4=he881be0_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - frozendict=2.4.2=py313h06a4308_0
  - giflib=5.2.2=hd590300_0
  - grapheme=0.6.0=pyhd8ed1ab_1
  - gsl=2.7=he838d99_0
  - hmmer=3.4=hb6cb901_4
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - infernal=1.1.5=pl5321h7b50bb2_4
  - intel-openmp=2025.0.0=h06a4308_1171
  - isa-l=2.31.1=hb9d3cd8_1
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=hfab0078_0
  - libblas=3.8.0=11_h86c2bf4_netlib
  - libcblas=3.8.0=11_h86c2bf4_netlib
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libidn2=2.3.8=hfac485b_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.43=h2797004_0
  - libsolv=0.7.30=he621ea3_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=hd590300_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - mpi=1.0=openmpi
  - ncbi-amrfinderplus=4.0.19=hf69ffd2_0
  - ncbi-vdb=3.3.0=h9948957_0
  - ncurses=6.4=h6a678d5_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - numexpr=2.14.1=py313h41d4191_0
  - numpy=2.3.5=py313h08c6c3d_0
  - numpy-base=2.3.5=py313h00548fb_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.3.3=py313h23c847b_1
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.42=hebb0a14_1
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hb9d3cd8_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-clone=0.46=pl5321hb9d3cd8_1
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-config-general=2.67=pl5321hdfd78af_0
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-config=0.008=pl5321ha770c72_0
  - perl-extutils-helpers=0.026=pl5321ha770c72_0
  - perl-extutils-installpaths=0.012=pl5321ha770c72_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-extutils-pl2bat=0.005=pl5321ha770c72_0
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.76=pl5321h5b5514e_1
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.214=pl5321h503566f_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321ha770c72_0
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-build-tiny=0.039=pl5321h166bdaf_0
  - perl-module-implementation=0.09=pl5321ha770c72_1
  - perl-module-runtime=0.016=pl5321ha770c72_1
  - perl-number-format=1.76=pl5321hd8ed1ab_0
  - perl-params-validate=1.31=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-readonly=2.05=pl5321ha770c72_0
  - perl-regexp-common=2017060201=pl5321hd8ed1ab_0
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-svg=2.87=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-text-format=0.63=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321h7b50bb2_6
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-xml-parser=2.44_01=pl5321hf2e2c51_1004
  - pigz=2.8=h2797004_0
  - piler-cr=1.06=h9948957_6
  - pip=25.0=py313h06a4308_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pyrodigal=3.6.3.post1=py313h366bbf7_1
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-isal=1.8.0=py313h07c4f96_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-zlib-ng=1.0.0=py313ha345abf_1
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py313h06a4308_1
  - rich=13.9.4=py313h06a4308_0
  - rpsbproc=0.5.0=h6a68c12_1
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - seqkit=2.12.0=he881be0_1
  - setuptools=78.1.1=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=py313h06a4308_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.67.1=py313h7040dfc_0
  - trnascan-se=2.0.12=pl5321h7b50bb2_2
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.6.1=py313h06a4308_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=py313h06a4308_0
  - xopen=2.0.2=pyh707e725_2
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h4ab18f5_6
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
prefix: /opt/conda
