name: MXD-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - wget
  - curl
  - bakta
  - blast
  - diamond
  - hmmer
  - prodigal        
  - pyrodigal        
  - trnascan-se
  - aragorn
  - infernal
  - ncbi-amrfinderplus
  - seqkit
  - pigz
  - pbzip2
  - sra-tools        
  - ncbi-datasets-cli 
  - biopython
  - pandas
  - numpy
  - tqdm
  - alive-progress
  - about-time
  - pyyaml
